[default]
# 工作目录
basedir = "."
# 日志目录，默认日志文件为myMon.log,旧版本有log_file项，如果同时设置了，会优先采用log_file
log_dir = "console"
# 配置报警忽略的metric项,依然会上报改metric，但原有的该metric项的报警策略将不会生效
ignore_file = "./falconignore"
# 保存快照(process, innodb status)的目录
snapshot_dir = "./snapshot"
# 保存快照的时间(日)
snapshot_day = 10
# 日志级别[RFC5424]
# 0 Emergency
# 1 Alert
# 2 Critical
# 3 Error
# 4 Warning
# 5 Notice
# 6 Informational
# 7 Debug
log_level = 7
log_file = "myMon.log"
# falcon agent连接地址
falcon_client = "http://127.0.0.1:1988/v1/push"
# 自定义endpoint
#endpoint=

[[mysql]]
user = "root"
password = "123456"
host = "192.168.1.1"
endpoint = "db-bj-test-st-payment-1"
port = 3306

[[mysql]]
user = "root"
password = "123456"
host = "192.168.1.2"
endpoint = "db-bj-test-st-payment-2"
port = 3306
